# Base used: https://github.com/derailed/k9s/blob/master/skins/dracula.yaml
---
foreground: &foreground "#cdd6f4"
background: &background "#1e1e2e"
current_line: &current_line "#1a1b26"
selection: &selection "#44475a"
comment: &comment "#6272a4"
cyan: &cyan "#8be9fd"
green: &green "#50fa7b"
orange: &orange "#fab387"
pink: &pink "#c462aa"
purple: &purple "#bd93f9"
red: &red "#f38ba8"
yellow: &yellow "#c462aa"

k9s:
  body:
    fgColor: *foreground
    bgColor: *background
    logoColor: *purple
  prompt:
    fgColor: *foreground
    bgColor: *background
    suggestColor: *purple
  info:
    fgColor: *pink
    sectionColor: *foreground
  dialog:
    fgColor: *foreground
    bgColor: *background
    buttonFgColor: *foreground
    buttonBgColor: *purple
    buttonFocusFgColor: *yellow
    buttonFocusBgColor: *pink
    labelFgColor: *orange
    fieldFgColor: *foreground
  frame:
    border:
      fgColor: *selection
      focusColor: *current_line
    menu:
      fgColor: *foreground
      keyColor: *pink
      numKeyColor: *pink
    crumbs:
      fgColor: *foreground
      bgColor: *current_line
      activeColor: *current_line
    status:
      newColor: *cyan
      modifyColor: *purple
      addColor: *green
      errorColor: *red
      highlightColor: *orange
      killColor: *comment
      completedColor: *comment
    title:
      fgColor: *foreground
      bgColor: *current_line
      highlightColor: *orange
      counterColor: *purple
      filterColor: *pink
  views:
    charts:
      bgColor: default
      defaultDialColors:
        - *purple
        - *red
      defaultChartColors:
        - *purple
        - *red
    table:
      fgColor: *foreground
      bgColor: *background
      header:
        fgColor: *foreground
        bgColor: *background
        sorterColor: *cyan
    xray:
      fgColor: *foreground
      bgColor: *background
      cursorColor: *current_line
      graphicColor: *purple
      showIcons: false
    yaml:
      keyColor: *pink
      colonColor: *purple
      valueColor: *foreground
    logs:
      fgColor: *foreground
      bgColor: *background
      indicator:
        fgColor: *foreground
        bgColor: *purple
        toggleOnColor: *green
        toggleOffColor: *cyan
