"$schema" = 'https://starship.rs/config-schema.json'

format = """
[░▒▓](section1_bg)\
$os\
[](fg:section1_bg bg:section2_bg)\
$directory\
[](fg:section2_bg bg:section3_bg)\
$git_branch\
$git_status\
$git_commit\
$git_state\
[](fg:section3_bg bg:section4_bg)\
$c\
$rust\
$golang\
$nodejs\
$php\
$java\
$kotlin\
$python\
$lua\
$ruby\
$terraform\
$helm\
[](fg:section4_bg bg:section5_bg)\
$time\
[ ](fg:section5_bg)\
$cmd_duration\
$line_break\
$character"""

palette = 'custom'
add_newline = false

[os]
disabled = false
style = "fg:section1_fg bg:section1_bg"

[os.symbols]
Ubuntu = " 󰕈 "
SUSE = "  "
Mint = " 󰣭 "
Manjaro = "  "
Linux = " 󰌽 "
Gentoo = " 󰣨 "
Fedora = " 󰣛 "
Alpine = "  "
Arch = " 󰣇 "
Artix = " 󰣇 "
CentOS = "  "
Debian = " 󰣚 "
Redhat = " 󱄛 "
RedHatEnterprise = " 󱄛 "

[directory]
style = "bold fg:section2_fg bg:section2_bg"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "

[git_branch]
symbol = ""
style = "bold fg:section3_fg bg:section3_bg"
format = '[ $symbol $branch ]($style)'

[git_status]
style = "bold fg:section3_fg bg:section3_bg"
format = '[($all_status$ahead_behind)]($style)'

[git_commit]
style = "bold fg:section3_fg bg:section3_bg"
format = '[ $hash$tag ]($style)'
only_detached = true
commit_hash_length = 5

[c]
symbol = " "
style = "bold fg:section4_fg bg:section4_bg"
format = '[ $symbol( $version) ]($style)'

[rust]
symbol = ""
style = "bold fg:section4_fg bg:section4_bg"
format = '[ $symbol( $version) ]($style)'

[golang]
symbol = ""
style = "bold fg:section4_fg bg:section4_bg"
format = '[ $symbol( $version) ]($style)'

[php]
symbol = ""
style = "bold fg:section4_fg bg:section4_bg"
format = '[ $symbol( $version) ]($style)'

[java]
symbol = " "
style = "bold fg:section4_fg bg:section4_bg"
format = '[ $symbol( $version) ]($style)'

[kotlin]
symbol = ""
style = "bold fg:section4_fg bg:section4_bg"
format = '[ $symbol( $version) ]($style)'

[haskell]
symbol = ""
style = "bold fg:section4_fg bg:section4_bg"
format = '[ $symbol( $version) ]($style)'

[python]
symbol = ""
style = "bold fg:section4_fg bg:section4_bg"
format = '[ $symbol( $version) ]($style)'

[nodejs]
symbol = "󰎙"
style = "bold fg:section4_fg bg:section4_bg"
format = '[ $symbol( $version) ]($style)'

[lua]
symbol = "󰢱"
style = "bold fg:section4_fg bg:section4_bg"
format = '[ $symbol( $version) ]($style)'

[ruby]
symbol = ""
style = "bold fg:section4_fg bg:section4_bg"
format = '[ $symbol( $version) ]($style)'

[terraform]
symbol = "󱁢"
style = "bold fg:section4_fg bg:section4_bg"
format = '[ $symbol( $version) ]($style)'

[helm]
symbol = ""
style = "bold fg:section4_fg bg:section4_bg"
format = '[ $symbol( $version) ]($style)'

[time]
disabled = true
time_format = "%R"
style = "fg:section5_fg bg:section5_bg"
format = '[  $time ]($style)'

[direnv]
symbol = " "
disabled = true
allowed_msg = ""
not_allowed_msg = ""
loaded_msg = "󱞸"
unloaded_msg = "󱞴"
style = "fg:section5_fg bg:section5_bg"
format = '[ $symbol $loaded - $allowed ]($style)'

[line_break]
disabled = true

[cmd_duration]
show_milliseconds = false
format = " in $duration "
disabled = false
show_notifications = false
min_time = 30000
min_time_to_notify = 60000

[character]
disabled = false
success_symbol = '[❯](bold fg:success_cmd)'
error_symbol = '[✗](bold fg:error_cmd)'

[palettes.custom]
section1_bg = "#a3aed2"
section1_fg = "#090c0c"

section2_bg = "#5c80c0"
section2_fg = "#e3e5e5"

section3_bg = "#394260"
section3_fg = "#769ff0"

section4_bg = "#212736"
section4_fg = "#769ff0"

section5_bg = "#1d2230"
section5_fg = "#a0a9cb"

success_cmd = "#a6e3a1"
error_cmd = "#f38ba8"
