---
tmux:
  symbols:
    branch: " "
    hashprefix: ":"
    ahead: " "
    behind: ""
    staged: "● "
    conflict: "✖ "
    modified: "✚ "
    untracked: " "
    stashed: "󰜦 "
    clean: ✔
    insertions: Σ
    deletions: " "
  styles:
    clear: "#[fg=default]"
    state: "#[fg=red,bold]"
    branch: "#[fg=white,bold]"
    remote: "#[fg=cyan]"
    divergence: "#[fg=default,bold]"
    staged: "#[fg=green,bold]"
    conflict: "#[fg=red,bold]"
    modified: "#[fg=red,bold]"
    untracked: "#[fg=magenta,bold]"
    stashed: "#[fg=cyan,bold]"
    clean: "#[fg=green,bold]"
    insertions: "#[fg=green]"
    deletions: "#[fg=red]"
  layout: [divergence, " - ", flags]
  options:
    branch_max_len: 0
    branch_trim: right
    ellipsis: …
    hide_clean: false
    swap_divergence: false
    divergence_space: false
    flags_without_count: false
