# https://mise.jdx.dev/configuration/settings.html

[_]
description = "system-wide packages"

[settings]
lockfile = true
auto_install = true
exec_auto_install = true
not_found_auto_install = true
fetch_remote_versions_cache = "1h"
fetch_remote_versions_timeout = "15s"
cache_prune_age = "30d"
always_keep_download = true
http_retries = 3
http_timeout = "30s"
jobs = 8
task_run_auto_install = true

[tools.usage]
version = "latest"

[tools."aqua:direnv/direnv"]
version = "latest"

[tools."aqua:go-task/task"]
version = "latest"

[tools."aqua:casey/just"]
version = "latest"

[tools."aqua:aws/aws-cli"]
version = "latest"

[tools."aqua:turbot/steampipe"]
version = "latest"
postinstall = "mise run steampipe:init"

[tools."aqua:cli/cli"]
version = "latest"
postinstall = "mise run github:init"

[tools."aqua:sxyazi/yazi"]
version = "latest"

[tools."aqua:starship/starship"]
version = "latest"

[tools."aqua:chmln/sd"]
version = "latest"

[tools."aqua:sharkdp/bat"]
version = "latest"

[tools."aqua:eza-community/eza"]
version = "latest"

[tools."aqua:juliosueiras/terraform-lsp"]
version = "latest"

[tools."aqua:dandavison/delta"]
version = "latest"

[tools."aqua:BurntSushi/ripgrep"]
version = "latest"

[tools."aqua:junegunn/fzf"]
version = "latest"

[tools."npm:@google/gemini-cli"]
version = "latest"

[tools."aqua:tfutils/tfenv"]
version = "latest"
postinstall = "mise run tfenv:init"

[tools."aqua:kubernetes/minikube"]
version = "latest"

[tools."aqua:kubernetes-sigs/kind"]
version = "latest"

[tools."aqua:derailed/k9s"]
version = "latest"

[tools."aqua:kubernetes-sigs/kustomize"]
version = "latest"

[tools."aqua:kcl-lang/cli"]
version = "latest"

[tools."aqua:kubernetes-sigs/krew"]
version = "latest"
postinstall = "mise run krew:init"

[tools."aqua:grafana/tanka"]
version = "latest"

[tools."aqua:jsonnet-bundler/jsonnet-bundler"]
version = "latest"

[tools."aqua:stefanprodan/timoni"]
version = "latest"

[tools."aqua:helm/helm"]
version = "latest"

[tools."aqua:helmfile/helmfile"]
version = "latest"

[tools."aqua:datreeio/datree"]
version = "latest"
