# https://mise.jdx.dev/configuration/settings.html

[_]
description = "system-wide packages"

[settings]
lockfile = true
auto_install = true
exec_auto_install = true
not_found_auto_install = true
fetch_remote_versions_cache = "1h"
fetch_remote_versions_timeout = "15s"
cache_prune_age = "30d"
always_keep_download = true
http_retries = 3
http_timeout = "30s"
jobs = 8
task_run_auto_install = true
experimental = true

[tools]
usage = "latest"
"aqua:direnv/direnv" = "latest"
"aqua:go-task/task" = "latest"
"aqua:casey/just" = "latest"
"aqua:aws/aws-cli" = "latest"
"aqua:turbot/steampipe" = { version = "latest", postinstall = "mise run steampipe:init" }
"aqua:cli/cli" = { version = "latest", postinstall = "mise run github:init" }
"aqua:sxyazi/yazi" = "latest"
"aqua:starship/starship" = "latest"
"aqua:chmln/sd" = "latest"
"aqua:sharkdp/bat" = { version = "latest", postinstall = "bat cache --build" }
"aqua:eza-community/eza" = "latest"
"aqua:dandavison/delta" = "latest"
"aqua:BurntSushi/ripgrep" = "latest"
"aqua:junegunn/fzf" = "latest"
"aqua:juliosueiras/terraform-lsp" = "latest"
"aqua:tfutils/tfenv" = { version = "latest", postinstall = "mise run tfenv:init" }
"aqua:kubernetes/minikube" = "latest"
"aqua:kubernetes-sigs/kind" = "latest"
"aqua:derailed/k9s" = "latest"
"aqua:kubernetes-sigs/kustomize" = "latest"
"aqua:kcl-lang/cli" = "latest"
"aqua:kubernetes-sigs/krew" = { version = "latest", postinstall = "mise run krew:init" }
"aqua:grafana/tanka" = "latest"
"aqua:jsonnet-bundler/jsonnet-bundler" = "latest"
"aqua:stefanprodan/timoni" = "latest"
"aqua:helm/helm" = "latest"
"aqua:helmfile/helmfile" = "latest"
"aqua:datreeio/datree" = "latest"
"aqua:tree-sitter/tree-sitter" = "latest"
"npm:@google/gemini-cli" = "latest"
"npm:@anthropic-ai/claude-code" = "latest"
